import { saveBytes, readUpload } from "@/lib/uploads";
import { prisma, getProfile } from "@/lib/db";
import { describeImageForDesign } from "@/lib/vision";

/**
 * Image generation for the card builder, via OpenAI's images API.
 *
 * The card builder is a Claude workload; this is the one place it reaches for
 * another provider, because a card that wants a hero, a texture or a spot
 * illustration otherwise has only the flat placeholder swatch. Called as a
 * TOOL during drafting, so the model decides when a card actually needs
 * artwork instead of every card paying for one.
 *
 * Generated bytes are downloaded and written to the upload volume, never
 * referenced by their OpenAI URL: those URLs expire within the hour, and the
 * coded-card sandbox's CSP allows only data: images anyway. Storing them makes
 * a generated image behave exactly like an uploaded photo.
 */

/** Ceiling per drafting call — artwork is the expensive part of a card. */
export const IMAGE_BUDGET = 2;

const ENDPOINT = "https://api.openai.com/v1/images/generations";

/** Unset key means the tool is simply not offered, not a broken builder. */
export function imageGenEnabled(): boolean {
  return Boolean(process.env.OPENAI_API_KEY);
}

export function imageModel(): string {
  return process.env.OPENAI_IMAGE_MODEL || "gpt-image-1";
}

/**
 * The generated image's aspect. Cards are 480px wide and rarely tall, so a
 * landscape hero is the common case; "square" suits an avatar or an icon.
 */
export type ImageShape = "landscape" | "square" | "portrait";

const SIZES: Record<ImageShape, string> = {
  landscape: "1536x1024",
  square: "1024x1024",
  portrait: "1024x1536",
};

/**
 * House style: where an image lands when the card doesn't ask for anything
 * else. These are DEFAULTS, not rules — flat textless artwork is the safe
 * choice for a card that will be re-themed under it, but a card that genuinely
 * wants a photoreal portrait, a full-bleed texture or its own wordmark should
 * get one. So the defaults are stated as preferences, and the closing line
 * hands the decision to the prompt whenever the prompt actually makes one.
 */
const STYLE_DEFAULTS =
  "Unless the description above asks otherwise, prefer: flat modern editorial illustration; "
  + "no text, letters, numbers or watermarks in the image; a simple composition with generous "
  + "negative space on a plain background; a restrained palette that sits comfortably behind "
  + "interface text; no 3D renders or drop shadows. "
  + "Where the description above explicitly calls for something different — photographic realism, "
  + "a dense full-bleed texture, a specific palette, lettering or a wordmark — follow the "
  + "description instead: it was written for this particular card and overrides these defaults.";

export type GeneratedImage = {
  /** Site-relative path, the same shape an uploaded photo's src takes. */
  src: string;
  /** What was actually asked for, surfaced to the admin in the draft note. */
  prompt: string;
};

/**
 * Generate one image and store it. Throws with an admin-readable message; the
 * builder turns that into a tool_result so the model can recover by drafting
 * the card without artwork rather than failing the whole draft.
 */
export async function generateCardImage(
  prompt: string,
  shape: ImageShape = "landscape",
): Promise<GeneratedImage> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error("Image generation is not configured (OPENAI_API_KEY is unset).");

  const cleaned = prompt.trim();
  if (!cleaned) throw new Error("An image needs a prompt describing what to draw.");

  const res = await fetch(ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({
      model: imageModel(),
      prompt: `${cleaned}\n\n${STYLE_DEFAULTS}`,
      size: SIZES[shape] ?? SIZES.landscape,
      n: 1,
    }),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`Image generation failed (${res.status}). ${detail.slice(0, 200)}`);
  }

  const body = (await res.json()) as { data?: { b64_json?: string; url?: string }[] };
  const first = body.data?.[0];
  if (!first) throw new Error("Image generation returned no image.");

  // gpt-image-1 returns base64; older models return a short-lived URL. Both
  // end up as stored bytes so the card never depends on a remote host.
  const bytes = first.b64_json
    ? Buffer.from(first.b64_json, "base64")
    : await downloadImage(first.url);

  const filename = await saveBytes(bytes, "image/png");
  return { src: `/api/uploads/${filename}`, prompt: cleaned };
}

async function downloadImage(url: string | undefined): Promise<Buffer> {
  if (!url) throw new Error("Image generation returned no image data.");
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Could not download the generated image (${res.status}).`);
  return Buffer.from(await res.arrayBuffer());
}

/**
 * An image the admin attached to the prompt. `src` is already on the upload
 * volume (the attach endpoint put it there), so "use it" costs nothing extra —
 * the model just writes the src into the card.
 *
 * `intent` is the admin's call, not the model's guess:
 * - "use": put this image in the card.
 * - "reference": look at it for style/layout direction, but don't embed it.
 * - "auto": the model decides from the description.
 */
export type PromptImage = {
  src: string;
  intent: "use" | "reference" | "auto";
};

export const IMAGE_INTENTS = ["use", "reference", "auto"] as const;

/**
 * Describe an attached image so the drafting model knows what it is. The
 * builder is a text conversation over many turns; reading the image once here
 * and passing prose forward is far cheaper than re-sending the bytes on every
 * turn, and it keeps the attachment useful for style direction ("match this
 * layout") as well as for embedding.
 *
 * Returns "" on any failure — an unreadable attachment must not kill a build,
 * since the admin's own words usually carry the intent anyway.
 */
export async function describePromptImage(src: string): Promise<string> {
  const name = src.replace(/^\/api\/uploads\//, "");
  const file = await readUpload(name);
  if (!file) return "";
  const ext = name.slice(name.lastIndexOf(".")).toLowerCase();
  return describeImageForDesign(file.bytes, ext);
}

/**
 * An image the owner already has. Generating artwork for something they have
 * a real photo of is both a waste and a downgrade — a card about a talk should
 * carry the actual photo of the talk. So the builder looks here FIRST and only
 * generates when the library has nothing suitable.
 */
export type LibraryImage = {
  /** Site-relative path, ready to drop into a card's src/imageUrl. */
  src: string;
  /** photo | project | source | headshot — where it came from. */
  origin: string;
  /** What it depicts, for the model to match against the card's subject. */
  description: string;
};

/** How many library matches one lookup returns — enough to choose from. */
const LIBRARY_LIMIT = 8;

/**
 * Every image the owner has, with the text that describes it. Photos carry a
 * Claude-vision description and a caption; projects and sources carry their
 * name and blurb. Matching is a plain case-insensitive term scan rather than
 * embeddings: the corpus is small (tens of rows, not thousands), and the model
 * reads the descriptions itself to make the final call.
 */
export async function findLibraryImages(query: string): Promise<LibraryImage[]> {
  const terms = query.toLowerCase().split(/\s+/).filter((t) => t.length > 2);
  const [photos, projects, sources, profile] = await Promise.all([
    prisma.photo.findMany({ orderBy: { order: "asc" } }),
    prisma.project.findMany({ where: { NOT: { imageUrl: null } }, orderBy: { order: "asc" } }),
    prisma.source.findMany({ where: { NOT: { imageUrl: null } }, orderBy: { createdAt: "desc" }, take: 40 }),
    getProfile().catch(() => null),
  ]);

  const all: LibraryImage[] = [
    ...photos.map((p) => ({
      src: `/api/uploads/${p.filename}`,
      origin: "photo",
      description: [p.caption, p.description].filter(Boolean).join(" — ") || "(no description)",
    })),
    ...projects.map((p) => ({
      src: p.imageUrl as string,
      origin: "project",
      description: `${p.name}: ${p.blurb.slice(0, 160)}`,
    })),
    ...sources.map((s) => ({
      src: s.imageUrl as string,
      origin: "source",
      description: `${s.title ?? "Source"}: ${(s.summary ?? "").slice(0, 160)}`,
    })),
  ];
  if (profile?.headshot) {
    all.push({
      src: profile.headshot,
      origin: "headshot",
      description: `Portrait of ${profile.name}${profile.tagline ? ` — ${profile.tagline}` : ""}`,
    });
  }

  // No usable terms (or no match) still returns the library, so the model can
  // browse what exists rather than being told "nothing found" for a vague ask.
  const scored = all
    .map((img) => ({
      img,
      score: terms.filter((t) => img.description.toLowerCase().includes(t)).length,
    }))
    .sort((a, b) => b.score - a.score);

  const matched = scored.filter((s) => s.score > 0);
  return (matched.length ? matched : scored).slice(0, LIBRARY_LIMIT).map((s) => s.img);
}
