import { saveBytes } from "@/lib/uploads";
import { prisma, getProfile } from "@/lib/db";

/**
 * Image generation for the card builder, via OpenAI's images API.
 *
 * The card builder is a Claude workload; this is the one place it reaches for
 * another provider, because a card that wants a hero, a texture or a spot
 * illustration otherwise has only the flat placeholder swatch. Called as a
 * TOOL during drafting, so the model decides when a card actually needs
 * artwork instead of every card paying for one.
 *
 * Generated bytes are downloaded and written to the upload volume, never
 * referenced by their OpenAI URL: those URLs expire within the hour, and the
 * coded-card sandbox's CSP allows only data: images anyway. Storing them makes
 * a generated image behave exactly like an uploaded photo.
 */

/** Ceiling per drafting call — artwork is the expensive part of a card. */
export const IMAGE_BUDGET = 2;

const ENDPOINT = "https://api.openai.com/v1/images/generations";

/** Unset key means the tool is simply not offered, not a broken builder. */
export function imageGenEnabled(): boolean {
  return Boolean(process.env.OPENAI_API_KEY);
}

export function imageModel(): string {
  return process.env.OPENAI_IMAGE_MODEL || "gpt-image-1";
}

/**
 * The generated image's aspect. Cards are 480px wide and rarely tall, so a
 * landscape hero is the common case; "square" suits an avatar or an icon.
 */
export type ImageShape = "landscape" | "square" | "portrait";

const SIZES: Record<ImageShape, string> = {
  landscape: "1536x1024",
  square: "1024x1024",
  portrait: "1024x1536",
};

/**
 * Style guidance appended to every prompt. The model writing the card cannot
 * see the visitor's theme, and a generated image cannot use CSS variables, so
 * artwork that carries its own text or a hard background will clash the moment
 * the owner switches themes. Steering toward flat, textless, transparent-ready
 * subjects is what keeps generated images theme-agnostic.
 */
const STYLE_RULES =
  "Flat modern editorial illustration. No text, letters, numbers, words, logos or watermarks anywhere in the image. " +
  "Simple composition with generous negative space and a plain uncluttered background. " +
  "Muted, desaturated palette that sits quietly behind interface text. No photorealism, no 3D renders, no drop shadows.";

export type GeneratedImage = {
  /** Site-relative path, the same shape an uploaded photo's src takes. */
  src: string;
  /** What was actually asked for, surfaced to the admin in the draft note. */
  prompt: string;
};

/**
 * Generate one image and store it. Throws with an admin-readable message; the
 * builder turns that into a tool_result so the model can recover by drafting
 * the card without artwork rather than failing the whole draft.
 */
export async function generateCardImage(
  prompt: string,
  shape: ImageShape = "landscape",
): Promise<GeneratedImage> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error("Image generation is not configured (OPENAI_API_KEY is unset).");

  const cleaned = prompt.trim();
  if (!cleaned) throw new Error("An image needs a prompt describing what to draw.");

  const res = await fetch(ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({
      model: imageModel(),
      prompt: `${cleaned}\n\n${STYLE_RULES}`,
      size: SIZES[shape] ?? SIZES.landscape,
      n: 1,
    }),
  });

  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`Image generation failed (${res.status}). ${detail.slice(0, 200)}`);
  }

  const body = (await res.json()) as { data?: { b64_json?: string; url?: string }[] };
  const first = body.data?.[0];
  if (!first) throw new Error("Image generation returned no image.");

  // gpt-image-1 returns base64; older models return a short-lived URL. Both
  // end up as stored bytes so the card never depends on a remote host.
  const bytes = first.b64_json
    ? Buffer.from(first.b64_json, "base64")
    : await downloadImage(first.url);

  const filename = await saveBytes(bytes, "image/png");
  return { src: `/api/uploads/${filename}`, prompt: cleaned };
}

async function downloadImage(url: string | undefined): Promise<Buffer> {
  if (!url) throw new Error("Image generation returned no image data.");
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Could not download the generated image (${res.status}).`);
  return Buffer.from(await res.arrayBuffer());
}

/**
 * An image the owner already has. Generating artwork for something they have
 * a real photo of is both a waste and a downgrade — a card about a talk should
 * carry the actual photo of the talk. So the builder looks here FIRST and only
 * generates when the library has nothing suitable.
 */
export type LibraryImage = {
  /** Site-relative path, ready to drop into a card's src/imageUrl. */
  src: string;
  /** photo | project | source | headshot — where it came from. */
  origin: string;
  /** What it depicts, for the model to match against the card's subject. */
  description: string;
};

/** How many library matches one lookup returns — enough to choose from. */
const LIBRARY_LIMIT = 8;

/**
 * Every image the owner has, with the text that describes it. Photos carry a
 * Claude-vision description and a caption; projects and sources carry their
 * name and blurb. Matching is a plain case-insensitive term scan rather than
 * embeddings: the corpus is small (tens of rows, not thousands), and the model
 * reads the descriptions itself to make the final call.
 */
export async function findLibraryImages(query: string): Promise<LibraryImage[]> {
  const terms = query.toLowerCase().split(/\s+/).filter((t) => t.length > 2);
  const [photos, projects, sources, profile] = await Promise.all([
    prisma.photo.findMany({ orderBy: { order: "asc" } }),
    prisma.project.findMany({ where: { NOT: { imageUrl: null } }, orderBy: { order: "asc" } }),
    prisma.source.findMany({ where: { NOT: { imageUrl: null } }, orderBy: { createdAt: "desc" }, take: 40 }),
    getProfile().catch(() => null),
  ]);

  const all: LibraryImage[] = [
    ...photos.map((p) => ({
      src: `/api/uploads/${p.filename}`,
      origin: "photo",
      description: [p.caption, p.description].filter(Boolean).join(" — ") || "(no description)",
    })),
    ...projects.map((p) => ({
      src: p.imageUrl as string,
      origin: "project",
      description: `${p.name}: ${p.blurb.slice(0, 160)}`,
    })),
    ...sources.map((s) => ({
      src: s.imageUrl as string,
      origin: "source",
      description: `${s.title ?? "Source"}: ${(s.summary ?? "").slice(0, 160)}`,
    })),
  ];
  if (profile?.headshot) {
    all.push({
      src: profile.headshot,
      origin: "headshot",
      description: `Portrait of ${profile.name}${profile.tagline ? ` — ${profile.tagline}` : ""}`,
    });
  }

  // No usable terms (or no match) still returns the library, so the model can
  // browse what exists rather than being told "nothing found" for a vague ask.
  const scored = all
    .map((img) => ({
      img,
      score: terms.filter((t) => img.description.toLowerCase().includes(t)).length,
    }))
    .sort((a, b) => b.score - a.score);

  const matched = scored.filter((s) => s.score > 0);
  return (matched.length ? matched : scored).slice(0, LIBRARY_LIMIT).map((s) => s.img);
}
